spring:
  application:
    name: scalable-task-manager-task-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stm_db
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none # Hibernate doesn't influence tables
      naming: # To prevent Hibernate from naming columns
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api/swagger.yml
server:
  port: 8081
user:
  service:
    url: http://localhost:8080