openapi: 3.0.3
info:
  title: Scalable Task Manager Task App
  version: "1.0"
paths:
  /v1/tasks:
    get:
      tags:
        - get
      operationId: getTasks
      summary: Gets all tasks
      responses:
        200:
          description: "Tasks were successfully retrieved"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskDTO"
        401:
          description: "Authentication failed"
        500:
          description: "A generic backend error occurred"
    post:
      tags:
        - create
      summary: Creates a new user
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDTO"
      responses:
        200:
          description: "User was successfully registered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        409:
          description: "Task with this data already exists"
        500:
          description: "A generic backend error occurred"
  /v1/tasks/{id}:
    get:
      tags:
        - get
      summary: Gets a task
      operationId: getTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: Id of the task
      responses:
        200:
          description: "Task was successfully retrieved"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        400:
          description: "Client did not send the server info correctly"
        401:
          description: "No authorization for this task"
        404:
          description: "Task not found"
        500:
          description: "A generic backend error occurred"
    delete:
      tags:
        - delete
      summary: Deletes a task
      operationId: deleteTask
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          description: Id of the task
          required: true
      responses:
        200:
          description: "Task was successfully deleted"
        400:
          description: "Client did not send the server info correctly"
        401:
          description: "No authorization for this task"
        404:
          description: "Task not found"
        500:
          description: "A generic backend error occurred"

components:
  schemas:
    TaskDTO:
      type: object
      required:
        - title
        - description
        - status
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
        creatorInfo:
          $ref: "#/components/schemas/UserDTO"
    UserDTO:
      type: object
      required:
        - id
        - fullName
        - username
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        username:
          type: string