openapi: 3.0.3
info:
  title: Scalable Task Manager Task App
  version: "1.0"
paths:
  /v1/tasks:
    get:
      tags:
        - get
      operationId: getTasks
      summary: Get all tasks
      responses:
        200:
          description: "Tasks were successfully retrieved"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskDTO"
        401:
          description: "Authentication failed"
        500:
          description: "A generic backend error occurred"
    post:
      tags:
        - create
      summary: Creates a new user
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDTO"
      responses:
        200:
          description: "User was successfully registered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        400:
          description: "Client did not send the server info correctly"
        500:
          description: "A generic backend error occurred"
components:
  schemas:
    TaskDTO:
      type: object
      required:
        - title
        - description
        - status
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
        creatorInfo:
          $ref: "#/components/schemas/UserDTO"
    UserDTO:
      type: object
      required:
        - id
        - fullName
        - username
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        username:
          type: string