spring:
  application:
    name: scalable-task-manager-user-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/stm_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update # Hibernate doesn't influence tables
      naming: # To prevent Hibernate from naming columns
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /api/swagger.yml