apiVersion: v1
kind: Service
metadata:
  name: task-app-service
spec:
  ports:
    - protocol: TCP
      port: 8081 # Port of the service, user by clients
      targetPort: 8081 # Port of the Spring application
      nodePort: 30007
  selector:
    app: task-app
  type: NodePort # Expose the service outside the cluster