apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080 # Port of the service, user by clients
      targetPort: 8080 # Port of the Spring application
      nodePort: 30007
  selector:
    app: user-app
  type: NodePort # Expose the service outside the cluster